/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Freepoly.org (https://sketchfab.com/blackrray)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-computer-02-freepolyorg-e55d089d02b5423b99c94ed56450aaa8
Title: Old Computer 02-Freepoly.org
*/

import { useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  const [x, setX] = useState(0)


  return (
    <group {...props} dispose={null} position={props.position} rotation={[0,0,0]}>
      <group rotation={[-Math.PI / 2, 0, -1.2]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials['06___Default']} />
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials['06___Default']} />
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials['06___Default']} />
          </group>
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials['03___Default']} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
